### ISSUE TITLE
Show tags

### ISSUE THREAD

**Issue by sphh** [FuturisticGoo/emotic#1]
Is there a way to show all tags for an emoticon (beside editing it)? E.g. by long pressing the emoticon? (And then it would be handy, if the tags were clickable and thus a new search with that tag starts ...)

**Comment by FuturisticGoo** [comment]
Currently there isn't a way besides the way you mentioned. It was indeed a feature I had in mind before, but I wasn't sure where and how to show it in clean manner, I'll look into it more.

**Comment by sphh** [comment]
Just one idea: The menu, which opens, when you tap and hold the emoticon, could also contain the tags for this emoticon. If you tap on a tag, the tag is appended to the text in the search field.

In this scenario, the edit menu item would be the last in the menu, because it is not that often used. The delete item could then go into the edit screen.

What do you think?

**Comment by FuturisticGoo** [comment]
Hmm that could work, but if there are many tags for that emoticon, the menu will get too long and that might look unwieldy. I'm thinking maybe it could be a suggestions list underneath the search bar when you tap on it, listing the tags alphabetically.  
Either like this
![image](https://github.com/user-attachments/assets/616d28e4-9949-41c3-aed2-482d572891a1)
  
Or this
![image](https://github.com/user-attachments/assets/fa1c5fdf-1f37-458d-acba-e84f23e710cd)
  
What do you think?

BTW, the search is pretty rudimentary right now, it treats the entire entered text as a single tag, multiple tags are not correctly handled. Guess I'm adding that to the TODO list :P

**Comment by sphh** [comment]
My original concern was, that I would like to see the tags of an emoticon.

I also find the idea to show possible search values (tags) for the search field. But isn't that another issue? Here I like the second suggestion better, because the menu could get very long.

**Comment by sphh** [comment]
> My preferred method for that would be the edit menu of the emoticon

I am only worried, that you might change something, when you just want to look up the tags. And that you cannot easily search for emoticons with the same tag.

> I don't understand, you mean showing tag suggestions while typing on the search field right? (if thats the case then thats what I meant with the mockup image above)

Yes, that's what I meant. I just noticed, that I haven't finished my first sentence in that paragraph. Sorry for the confusion it has caused!

**Comment by FuturisticGoo** [comment]
Oof I took a while didn't I? Life happens ≖‿≖    
Anyway I thought your idea was nice, so I implemented that in a similar way as you described. Update will hit F-droid in a few days.

**Comment by FuturisticGoo** [comment]
v0.1.3 is now on F-droid, so I'm gonna close this. Hopefully the implementation is similar to what you imagined :)

**Comment by sphh** [comment]
I just found the time to play around with it. IMHO this is great! Thanks!
