### ISSUE TITLE
Small screens ...

### ISSUE THREAD

**Issue by sphh** [FuturisticGoo/emotic#2]
If I edit an emoticon on my tiny phone, I get the following:
![Screenshot_20241006-104923](https://github.com/user-attachments/assets/9a4ab9b0-b5ba-4ef5-980f-e45b5c0be89c)

The edit part is not scrollable.

The phone is a Unihertz Jelly Pro with a 240px·432px screen.

**Comment by FuturisticGoo** [comment]
Oh wow I never expected this app to be used on such a tiny phone, (which I gotta admit is pretty cool ^_^ ).   
I'm gonna add some checks to make the app more responsive. Thanks for bringing this to my attention!
