### ISSUE TITLE
0.1.3 apk is not signed?

### ISSUE THREAD

**Issue by linsui** [FuturisticGoo/emotic#6]
I can't verify it with apksigner.

```
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
```

Could you please take a look? Thanks!

**Comment by FuturisticGoo** [comment]
Ugh that's embarrassing. I believe I built and uploaded the unsigned flavour. 
I've replaced the old release apks with the signed apks. Will F-droid use that or should I push another tag? @linsui 
Also @eqoffical yes it's because of this.

**Comment by linsui** [comment]
You have NDK installed in your build environment so that the build is not reproducible. Which ndk version do you use?

**Comment by FuturisticGoo** [comment]
I've removed the NDK and recompiled it, there's a small difference in the binary. I've reuploaded them to the release.  
NDK was version 25.0.8775105 btw.

**Comment by linsui** [comment]
Thanks!
